---
# tasks file for builder
- name: "Update cache"
  ansible.builtin.apt:
    update_cache: yes

- name: "Ensure install git"
  ansible.builtin.apt:
    name: 'git'
    state: present

- name: "Ensure install Java VM"
  ansible.builtin.apt:
    name: default-jdk
    state: latest

- name: "Ensure install s3fs"
  ansible.builtin.apt:
    name: s3fs
    state: latest

- name: "Create directory for yandex bucket"
  ansible.builtin.file:
    path: "{{ bucket_folder }}"
    state: directory
    mode: '0755'

- name: "Set env for maven"
  ansible.builtin.lineinfile:
    path: "/etc/environment"
    state: present
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  with_items: "{{ maven_env }}"

- name: "Create directory for maven"
  ansible.builtin.file:
    path: "{{ maven_folder }}"
    state: directory
    mode: '0755'

- name: "Create directory for maven archive"
  ansible.builtin.file:
    path: "{{ maven_archive_folder }}"
    state: directory
    mode: '0755'

- name: "Download required maven"
  ansible.builtin.get_url:
    url: "{{ maven_link }}"
    dest: "{{ maven_archive_folder }}"
    checksum: "{{ maven_sha }}"
    validate_certs: no

- name: "Unpack maven archive"
  ansible.builtin.unarchive:
    src: "{{ maven_archive_distr }}"
    dest: "{{ maven_folder }}"
    remote_src: yes
    extra_opts:
      - --strip-components=1

- name: "Create link maven to bin"
  ansible.builtin.file:
    src: "{{ mvn }}"
    dest: '/bin/mvn'
    state: link

- name: "Create directory for gitclone"
  ansible.builtin.file:
    path: "{{ git_clone_tmp }}"
    state: directory
    mode: '0755'

- name: "Clone github repository"
  ansible.builtin.git:
    repo: "{{ git_clone_url }}"
    dest: "{{ git_clone_tmp }}"
    clone: yes
    update: no

- name: "Build java project"
  command: 'mvn package'
  args:
    chdir: "{{ git_clone_tmp }}"

- name: "Send s3fs file to build"
  ansible.builtin.copy:
    src: '{{ s3fs_file }}'
    dest: '{{ tmp_path }}'

- name: "Change permission on s3fs file"
  ansible.builtin.file:
    path: '{{ s3fs_rem }}'
    mode: '600'

- name: "Get yandex bucket resource"
  command: 's3fs devopsdb /tmp/mnt -o passwd_file=/tmp/.passwd-s3fs -o url=http://storage.yandexcloud.net -o use_path_request_style'

- name: "Get war files from build folder"
  ansible.builtin.find:
    path: "{{ git_maven_target }}"
    use_regex: yes
    patterns: "^.*?\\.(?:war|jar)$"
  register: build_files

- name: "Copy war|jar files to yandex bucket"
  ansible.builtin.copy:
    src: '{{ item.path }}'
    dest: '{{ bucket_folder }}'
    remote_src: yes
  with_items: '{{ build_files.files }}'

- name: "Unset yandex bucket resource"
  command: 'umount /tmp/mnt'